# Automatically trigger the pipeline when a push is made to the 'main' branch
trigger:
  branches:
    include:
      - main

# Also run the pipeline when a Pull Request targets the 'main' branch
pr:
  branches:
    include:
      - main

# Define runtime parameters that can be set when running the pipeline manually
parameters:
  - name: BuildEnvironment              # Choose the environment to deploy to: dev or prod
    type: string
    default: 'dev'
    values:
      - dev
      - prod

  - name: tag                           # Docker image tag to use
    type: string
    default: 'latest'

# Define global variables
variables:
  imageName: 'deemaa/polybot-dev'
  imageNameprod: 'deemaa/polybot-prod'
  DOCKERHUB_USERNAME: $(DOCKERHUB_USERNAME)  # Pulled from Azure DevOps secret variable
  DOCKERHUB_TOKEN: $(DOCKERHUB_TOKEN)        # Pulled from Azure DevOps secret variable

stages:

  # Stage for building and deploying to the dev environment
  - stage: Build_Dev
    displayName: Build & Deploy to Dev
    condition: eq('${{ parameters.BuildEnvironment }}', 'dev')  # Run only if 'dev' is selected
    jobs:
      - job: BuildJobDev
        steps:
          - script: |
              echo "Deploying to Dev..."
              echo "Image: $(imageName)"
              echo "Tag: ${{ parameters.tag }}"

  # Stage for building and deploying to the prod environment (requires approval)
  - stage: Build_Prod
    displayName: Build & Deploy to Prod
    condition: eq('${{ parameters.BuildEnvironment }}', 'prod')  # Run only if 'prod' is selected
    jobs:
      - deployment: DeployToProd
        environment: prod      # Azure environment named 'prod' with manual approval enabled
        strategy:
          runOnce:
            deploy:
              steps:
                - script: |
                    echo "Deploying to Production..."
                    echo "Image: $(imageNameprod)"
                    echo "Tag: ${{ parameters.tag }}"
